### PR TITLE
Dialing computer

### PR DESCRIPTION
**Pull request by nosknut**

### CODE REVIEW

**Comment by DraksterAU** [comment]
Sorry nosknut, I've looked through this and I'm not willing to use it on the public stargate network.

An Automated GDO system for any stargate on a homeworld with an iris is coming soon!

**Comment by nosknut** [comment]
Im not gonna make to mutch mess of it, but why not XD. I doubt the code is a problem. But if u are implementing a gdo system, can you get someone to make it encrypted insted of having to get the ip?






Sendt fra Windows E-post





Fra: DraksterAU
Sendt: ‎mandag‎, ‎11‎. ‎januar‎ ‎2016 ‎12‎:‎53
Til: StargateMC/Server
Kopi: nosknut





Sorry nosknut, I've looked through this and I'm not willing to use it on the public stargate network.

An Automated GDO system for any stargate on a homeworld with an iris is coming soon!

**Comment by DraksterAU** [comment]
@nosknut This will include an Automated GDO that recognises  the player, bypassing the need for passwords or encryption.

**Comment by nosknut** [comment]
YES!!! Thats wt i was working on aft first XD. How the … did you do it XD






Sendt fra Windows E-post





Fra: DraksterAU
Sendt: ‎tirsdag‎, ‎12‎. ‎januar‎ ‎2016 ‎06‎:‎47
Til: StargateMC/Server
Kopi: nosknut





@nosknut This will include an Automated GDO that recognises the player, bypassing the need for passwords or encryption.

**Pull request closed without merging**
